---
abstract: 'Build a distribution like CJM'
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-CJM
requires:
  Dist::Zilla: 4.200001
  Dist::Zilla::Plugin::ArchiveRelease: 0.08
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::GitVersionCheckCJM: 3.02
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::MakeMaker: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MatchManifest: 4.00
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodLoom: 4.00
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::Repository: 0.16
  Dist::Zilla::Plugin::TemplateCJM: 3.05
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::Plugin::VersionFromModule: 0.08
  Dist::Zilla::PluginBundle::Git: 1.103520
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Git::Wrapper: 0
  Moose: 0.65
  Moose::Autobox: 0.09
resources:
  repository: git://github.com/madsen/dist-zilla-pluginbundle-cjm.git
version: 4.02
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::VersionFromModule
      name: '@CJM/VersionFromModule'
      version: 0.08
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@CJM/GatherDir'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@CJM/PruneCruft'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@CJM/ManifestSkip'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@CJM/MetaJSON'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@CJM/MetaYAML'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::License
      name: '@CJM/License'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@CJM/PodSyntaxTests'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@CJM/PodCoverageTests'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@CJM/ExtraTests'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PodLoom
      config:
        Pod::Loom version: 0.04
      name: '@CJM/PodLoom'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@CJM/MakeMaker'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@CJM/MetaConfig'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MatchManifest
      name: '@CJM/MatchManifest'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::GitVersionCheckCJM
      name: '@CJM/GitVersionCheckCJM'
      version: 3.05
    -
      class: Dist::Zilla::Plugin::TemplateCJM
      name: '@CJM/TemplateCJM'
      version: 3.05
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@CJM/Repository'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@CJM/@Git/Check'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@CJM/@Git/Commit'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@CJM/@Git/Tag'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@CJM/@Git/Push'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@CJM/TestRelease'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@CJM/UploadToCPAN'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@CJM/ArchiveRelease'
      version: 3.01
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.200006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200006
